#%RAML 1.0
---
title: Wilson Tesoreria
baseUri: http://localhost:500/api/
version: v1 

traits:
  withAuthHeaders:
    headers:
      Authorization:
        description: Auth token with the credential returned
        type: string
/status:
  description: check if you're connected
  get:
    description: varify if you have connection
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "connected"
              }
/user_token:
  description: Token creation
  post:
      description: Create new token for user.
      body:
        application/json:
          example: |
            {
                "email": "Admin@admin.com",
                "password": "1234" 
            }
      responses:
        201:
          body:
            application/json:
              example: |
                {
                    "message": "User token",
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NjY5MjY0MTMsInN1YiI6MSwiZW1haWwiOiJBZG1pbkBhZG1pbi5jb20ifQ.AvlpUsZ1mF53XCU9VjNxR3lxHKe05gt2jsl56YRkhxI"
                }
        404:
            body:
                application/json:
                  example: |
                    {
                        "message": "User Don't found"
                    }
/users:
  description: Users related endpoints / Must be logged in and with a token
  post:
    is: [withAuthHeaders]
    description: Create new users
    body:
          application/json:
            example: |
              {
                    "name": "james1",
                    "email": "james1@gmail.com",
                    "password": "1234",
                    "typeUserId": "1",
              }
    responses:
      202:
        body:
            application/json:
              example: |
                {
                    "message": "User created",
                    "user": {
                        "id": 2,
                        "name": "james1",
                        "email": "james1@gmail.com",
                        "password": "$2a$12$oZq09XlozD19pcYlYwrEBe2/lr6Y2ETNgT.hW.uaFGUKdjDSWzqRS",
                        "type_user_id": 1
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
  get:
    is: [withAuthHeaders]
    description: Retrieve all users excepting current user
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "message": "All users",
                    "data": [
                      {
                          "id": 1,
                          "name": "james",
                          "email": "james@gmail.com",
                          "password": "$2a$12$oZq09XlozD19pcYlYwrEBe2/lr6Y2ETNgT.hW.uaFGUKdjDSWzqRS",
                          "type_user_id": 1
                      },
                      {
                          "id": 2,
                          "name": "james1",
                          "email": "james1@gmail.com",
                          "password": "$2a$12$oZq09XlozD19pcYlYwrEBe2/lr6Y2ETNgT.hW.uaFGUKdjDSWzqRS",
                          "type_user_id": 1
                      }
                    ]
                }
      400:
          body:
                application/json:
                  example: |
                    {
                        "message": "Error at DB"
                    }
      500:
          body:
                application/json:
                  example: |
                    {
                        "message": "Internal server error"
                    }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
/users/:id:
  description: Individual user endpoint
  get:
    is: [withAuthHeaders]
    description: search an specific user
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "id": 2,
                    "name": "james1",
                    "email": "james1@gmail.com",
                    "password": "$2a$12$oZq09XlozD19pcYlYwrEBe2/lr6Y2ETNgT.hW.uaFGUKdjDSWzqRS",
                    "type_user_id": 1
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "user not finded"
                    }
  delete:
    is: [withAuthHeaders]
    description: Delete an specific user
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "message": "user deleted"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "user not finded"
                    }             
/users/types:
  description: All type of users endpoint
  get:
    is: [withAuthHeaders]
    description: Retrieve all type of users
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "message": "All type of users",
                    "data": [
                      {
                          "id": 1,
                          "name": "TVO"
                      },
                      {
                          "id": 2,
                          "name": "Fanatiz"
                      }
                    ]
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      400:
        body:
                application/json:
                  example: |
                    {
                        "message": "Error at DB"
                    }
  post:
    is: [withAuthHeaders]
    description: Create new type of user
    body:
          application/json:
            example: |
              {
                    "name": "Super admin"
              }
    responses:
      201:
        body:
            application/json:
              example: |
                {
                    "message": "New type of user created",
                    "type_user": {
                        "id": 2,
                        "name": "Super admin"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
/users/types/:id:
  description: Specific type of user endpoint
  get:
    is: [withAuthHeaders]
    description: Search an specific type of user
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "id": 1,
                    "name": "admin"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "type of user not finded"
                    }
  delete:
    is: [withAuthHeaders]
    description: Delete an specific type of user
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "message": "type of user deleted"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "type of user not finded"
                    }
/proveedores:
  description: Proveedores related endpoints / Must be loged in and with a token
  post:
    is: [withAuthHeaders]
    description: Create new proovedores
    body:
          application/json:
            example: |
              {
                    "name": "fanatiz"
              }
    responses:
      201:
        body:
            application/json:
              example: |
                {
                    "message": "proveedor created",
                    "proveedor": {
                        "id": 2,
                        "name": "fanatiz"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
  get:
    is: [withAuthHeaders]
    description: Retrieve all proveedores
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "message": "All proveedores",
                    "data": [
                      {
                          "id": 1,
                          "name": "Fanatiz"
                      },
                      {
                          "id": 2,
                          "name": "Joy"
                      }
                    ]
                }
      404:
          body:
                application/json:
                  example: |
                    {
                        "message": "Not proveedores found"
                    }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      500:
          body:
                application/json:
                  example: |
                    {
                        "message": "Internal server error"
                    }

/proveedores/:id:
  description: Individual proveedor enpoint
  get:
    is: [withAuthHeaders]
    description: Search an specific proveedor
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "id": 2,
                    "name": "fanatiz"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "Proveedor not finded"
                    }
  delete:
    is: [withAuthHeaders]
    description: Delete an specific proveedor
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "message": "proveedor deleted"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "proveedor not finded"
                    }

/empresas:
  description: All empresas endpoint
  get:
    is: [withAuthHeaders]
    description: Search all empresas
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "message": "All empresas",
                    "data": [
                      {
                          "id": 1,
                          "name": "Fanatiz"
                      },
                      {
                          "id": 2,
                          "name": "Joy"
                      }
                    ]
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "Not empresas found"
                    }
  post:
    is: [withAuthHeaders]
    description: Create new empresa
    body:
          application/json:
            example: |
              {
                    "nombre": "fanatiz"
              }
    responses:
      201:
        body:
            application/json:
              example: |
                {
                    "message": "empresa created",
                    "empresa": {
                        "id": 2,
                        "name": "fanatiz"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
/empresas/:id:
  description: Specific empresa endpoint
  get:
    is: [withAuthHeaders]
    description: Search an specific empresa
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "id": 2,
                    "name": "fanatiz"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "empresa not finded"
                    }
  delete:
    is: [withAuthHeaders]
    description: Delete an specific empresa
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "message": "Empresa deleted"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "empresa not finded"
                    }
/facturas:
  description: All facturas endpoint
  get:
    is: [withAuthHeaders]
    description: Retrieve all facturas
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "message": "All facturas",
                    "data": [
                      {
                          "id": 1,
                          "numero": 1,
                          "proveedor": 1,
                          "currency": "usd",
                          "monto": 200,
                          "detalle": "pago",
                          "fecha": 1232190830,
                          "vencimiento": 123123123,
                          "status": "por pagar",
                          "empresa": 1
                      },
                      {
                          "id": 2,
                          "numero": 2,
                          "proveedor": 2,
                          "currency": "usd",
                          "monto": 200,
                          "detalle": "pago",
                          "fecha": 1232190830,
                          "vencimiento": 123123123,
                          "status": "por pagar",
                          "empresa": 1
                      }
                    ]
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "Not facturas found"
                    }
/facturas/:id:
  description: Individual factura endpoint
  get:
    is: [withAuthHeaders]
    description: Search an specific factura
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "id": 2,
                    "numero": 2,
                    "proveedor": 2,
                    "currency": "usd",
                    "monto": 200,
                    "detalle": "pago",
                    "fecha": 1232190830,
                    "vencimiento": 123123123,
                    "status": "por pagar",
                    "empresa": 1
                  }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "factura not finded"
                    }
  delete:
    is: [withAuthHeaders]
    description: Delete an specific factura
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "message": "factura deleted"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "factura not finded"
                    }
/currencies:
  description: All currencies endpoint
  get:
    is: [withAuthHeaders]
    description: Retrieve all currencies
    responses:
      200:
        body:
            application/json:
              example: |
                {
                  "message": "All currencies",
                  "data": [
                      {
                          "id": 1,
                          "name": "Dolar Americano",
                          "symbol": "USD"
                      }
                    ]
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "Not currencies found"
                    }
  post:
    is: [withAuthHeaders]
    description: Create new currency
    body:
          application/json:
            properties:
              name:
                description: name of the currency
                type: string
                required: true
              symbol:
                description: symbol of the currency
                type: string
                required: true
            example: |
              {
                    "name": "Peso chileno",
                    "symbol": "CLP"
              }
    responses:
      201:
        body:
            application/json:
              example: |
                {
                    "message": "currency created",
                    "currency": {
                        "id": 2,
                        "name": "Peso chileno",
                        "symbol": "CLP"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
/currencies/:id:
  get:
    is: [withAuthHeaders]
    description: Retrieve all currencies
    queryParameters:
      id:
        description: id of the currency
        type: int
        required: true
    responses:
      200:
        body:
            application/json:
              example: |
               {
                  "id": 1,
                  "name": "Dolar Americano",
                  "symbol": "USD
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "currency not finded"
                    }
  delete:
    is: [withAuthHeaders]
    description: Retrieve all currencies
    queryParameters:
      id:
        description: id of the currency
        type: int
        required: true
    responses:
      200:
        body:
            application/json:
              example: |
                {
                    "message": "currency deleted"
                }
      403:
        body:
                application/json:
                  example: |
                    {
                        "message": "Token Invalid"
                    }
      404:
        body:
                application/json:
                  example: |
                    {
                        "message": "currency not finded"
                    }